Akhigbepeace/Wavecrest

src/App.css, src/App.js, src/Pages/ApplyNow.jsx, src/Pages/Career/index.jsx, src/Pages/Home/DiscoverHospitality.jsx, src/Pages/Home/Footer.jsx, src/Pages/Home/Partners.jsx, src/Pages/Home/Showcase.jsx, src/Pages/SupportUs.jsx, src/components/layouts/Navbar.jsx
- Reduced number of files changed on Home Page
-
=> Reduced number of files changed on Home Page

src/App.js, src/Pages/Academics/Programmes.jsx, src/Pages/CertificateCoursesDesc.jsx, src/Pages/HNDProgrammeDesc.jsx, src/Pages/NDProgrammeDesc.jsx
- Created **programme description pages** for each programme on `Academics page`
=> Created Programmes Page

src/Pages/About/Index.jsx, src/Pages/About/Milestone/Milestone.jsx, src/Pages/About/Our Team/Board.jsx, src/Pages/About/Our Team/Management.jsx, src/Pages/About/Our Team/Staff.jsx, src/Pages/About/Our Team/index.jsx, src/Pages/About/Profile/Index.jsx, src/Pages/About/Profile/OurPhilosophy.jsx, src/Pages/Academics/Index.jsx, src/Pages/Academics/Internship.jsx, src/Pages/Academics/NYSC.jsx, src/Pages/Academics/Programmes.jsx, src/Pages/Academics/Training.jsx, src/Pages/Admission/AdmissionRequirements.jsx, src/Pages/Admission/ApplyOnline.jsx, src/Pages/Admission/FAQs.jsx, src/Pages/Admission/Hostel.jsx, src/Pages/Admission/Index.jsx, src/Pages/Admission/Tuition And Scholarship/RespTuition.jsx, src/Pages/Career/index.jsx, src/Pages/Career/postJobVacancies.jsx, src/Pages/Career/viewJobVacancies.jsx, src/Pages/CertificateCoursesDesc.jsx, src/Pages/Contact.jsx, src/Pages/HNDProgrammeDesc.jsx, src/Pages/Home/StudyProgrammes.jsx, src/Pages/NDProgrammeDesc.jsx, src/Pages/ViewVacancies.jsx, src/components/Navbar.jsx
- Started working on the nested links on the mobile navbar
- Created the banner for each mobile pages indicating current page
=> Created Banner for each mobile pages

src/Pages/About/Our Team/Media Query/Responsive Board.jsx, src/Pages/About/Our Team/Media Query/Responsive Management.jsx, src/Pages/About/Our Team/Media Query/Responsive Staff.jsx, src/Pages/About/Profile/Gallery.jsx
- Fixed the number of slides that shows on mobile screen on `Our Team` component and `Gallery` component
=> Fixed the number of slides

src/App.js, src/Pages/About/Milestone/Responsive Milestone/Eighties.jsx, src/Pages/About/Milestone/Responsive Milestone/Nineties.jsx, src/Pages/About/Milestone/Responsive Milestone/Seventies.jsx, src/Pages/About/Milestone/Responsive Milestone/Twenties.jsx, src/Pages/About/Milestone/Responsive Milestone/TwentyTens.jsx, src/Pages/About/Our Team/Media Query/Responsive Board.jsx, src/Pages/About/Our Team/Media Query/Responsive Management.jsx, src/Pages/About/Our Team/Media Query/Responsive Staff.jsx, src/Pages/About/Profile/OurPhilosophy.jsx, src/Pages/Academics/NYSC.jsx, src/Pages/Academics/Training.jsx, src/Pages/Admission/ApplyOnline.jsx, src/Pages/Admission/FAQs.jsx, src/Pages/Admission/Hostel.jsx, src/Pages/Blog.jsx, src/Pages/Career/postJobVacancies.jsx, src/Pages/Career/viewJobVacancies.jsx, src/Pages/Contact.jsx, src/Pages/Home/Partners.jsx, src/Pages/Home/Showcase.jsx, src/Pages/Home/StudyProgram/Courses.jsx, src/Pages/Home/StudyProgram/ShortCourses.jsx, src/Pages/HostelApplication.jsx, src/Pages/ViewVacancies.jsx, src/components/Navbar.jsx, src/components/Search.jsx
- Fixed `Sliders` on `Our Team` component for mobile
- 
- Fixed `Sliders` on `Milestone` component for mobile
- 
- Cleared out all input fields on form submission
- Started working on displaying `topPosts` and `Posts` related to each `Category` on `Blog` page
=> Fixed Carousel Slider on about page

src/Pages/About/Our Team/Board.jsx, src/Pages/About/Our Team/Staff.jsx, src/Pages/About/Profile/OurPhilosophy.jsx, src/Pages/Academics/Internship.jsx, src/Pages/Academics/Programmes.jsx, src/Pages/Academics/Training.jsx, src/Pages/Admission/AdmissionRequirements.jsx, src/Pages/Admission/ApplyOnline.jsx, src/Pages/Admission/Hostel.jsx, src/Pages/Admission/Tuition And Scholarship/TuitionAndScholarship.jsx, src/Pages/Blog.jsx, src/Pages/BlogPost.jsx, src/Pages/Career/postJobVacancies.jsx, src/Pages/Career/viewJobVacancies.jsx, src/Pages/CertificateCoursesDesc.jsx, src/Pages/Contact.jsx, src/Pages/HNDProgrammeDesc.jsx, src/Pages/Home/OurStories.jsx, src/Pages/Home/Showcase.jsx, src/Pages/Home/StudyProgram/Courses.jsx, src/Pages/Home/StudyProgram/ShortCourses.jsx, src/Pages/Home/StudyProgram/StudyProgrammes.jsx, src/Pages/HostelApplication.jsx, src/Pages/NDProgrammeDesc.jsx, src/Pages/SupportUs.jsx, src/Pages/ViewVacancies.jsx, src/components/Footer.jsx, src/components/Navbar.jsx, src/components/ShowcaseSlider.jsx
- Displayed `posts` and `Top Posts` on click on any `Category` on the `Blog` Page.
- Started implementation of `Form Validation` on `Contact` page.
- Used `useNavigate()` in place of `Links` for my navigation.
- Linked each `Caption Heading` for COURSES on `Study Programmes` component to their respective `Course Description` page.
- Linked each `Caption Heading` for TRAINING on `Study Programmes` component to the `Training` tab on the `Academics` page.
=> Added a new feature on blogs component

src/Pages/About/Milestone/Milestone.jsx, src/Pages/About/Our Team/Management.jsx, src/Pages/About/Profile/Index.jsx, src/Pages/Academics/Internship.jsx, src/Pages/Academics/NYSC.jsx, src/Pages/Academics/Programmes.jsx, src/Pages/Academics/Training.jsx, src/Pages/Admission/AdmissionRequirements.jsx, src/Pages/Admission/ApplyOnline.jsx, src/Pages/Admission/FAQs.jsx, src/Pages/Admission/Hostel.jsx, src/Pages/Admission/Tuition And Scholarship/RespTuition.jsx, src/Pages/Admission/Tuition And Scholarship/TuitionAndScholarship.jsx, src/Pages/Career/postJobVacancies.jsx, src/Pages/Career/viewJobVacancies.jsx, src/Pages/ViewVacancies.jsx
- Removed `N.B.` on `Internship` and `NYSC` component on the `Academics` page.
- Created Button for easy navigation to nested pages for pages that has nested links
- 
- 
-
=> Created Buttons for easy navigation on Mobile

package.json, src/API/axiosInstance.js, src/Pages/About/Index.jsx, src/Pages/About/Milestone/Milestone.jsx, src/Pages/About/Our Team/index.jsx, src/Pages/About/Profile/Index.jsx, src/Pages/Academics/Index.jsx, src/Pages/Academics/Internship.jsx, src/Pages/Academics/NYSC.jsx, src/Pages/Academics/Programmes.jsx, src/Pages/Academics/Training.jsx, src/Pages/Admission/AdmissionRequirements.jsx, src/Pages/Admission/ApplyOnline.jsx, src/Pages/Admission/FAQs.jsx, src/Pages/Admission/Hostel.jsx, src/Pages/Admission/Index.jsx, src/Pages/Admission/Tuition And Scholarship/TuitionAndScholarship.jsx, src/Pages/Blog.jsx, src/Pages/BlogPost.jsx, src/Pages/Career/postJobVacancies.jsx, src/Pages/Contact.jsx, src/Pages/Home/Index.jsx, src/Pages/Home/Showcase.jsx, src/Pages/Home/StudyProgram/ShortCourses.jsx, src/Pages/HostelApplication.jsx, src/Pages/ViewVacancies.jsx, src/components/Navbar.jsx, src/components/PopupModal.jsx, yarn.lock
- Added popover on loading of page
- Fixed a bug on mobile sidebar
- Started data from API for home page
-
=> Ft popover blogpost

src/App.js, src/Pages/About/Our Team/Media Query/Responsive Staff.jsx, src/Pages/Admission/Tuition And Scholarship/TuitionAndScholarship.jsx, src/Pages/Blog.jsx, src/Pages/BlogPost.jsx, src/Pages/Home/OurStories.jsx, src/Pages/Home/StudyProgram/StudyProgrammes.jsx, src/components/BlogSideBar.jsx, src/components/Navbar.jsx, src/data/blog.js, yarn.lock
- Fixed issue on blog post page and navbar
=> Fx blog post

src/App.js, src/Pages/About/Our Team/Media Query/Responsive Management.jsx, src/Pages/About/Our Team/Media Query/Responsive Staff.jsx, src/Pages/About/Our Team/Staff.jsx, src/Pages/Home/Blog.jsx, src/Pages/Home/Index.jsx, src/Pages/Home/Showcase.jsx, src/components/PopupModal.jsx
- Started working on modal popover
- Changed object fit of staff images 
- Replaced a management picture
- Added extra images for staffs
- Increased the size of the fliers on News container on `Home` page
- Fixed Navbar issue for mobile
-
=> Fx staff image

src/App.js, src/Pages/Admission/AdmissionRequirements.jsx, src/Pages/Admission/ApplyOnline.jsx, src/Pages/Admission/FAQs.jsx, src/Pages/Admission/Tuition And Scholarship/TuitionAndScholarship.jsx, src/Pages/HostelApplication.jsx, src/components/PopupModal.jsx
- Fixed modal popover 
- Corrected some errors on `Apply Online`, `AdmissionRequirements`, `FAQ`, `Hostel Application` and `TuitionAndScholarship` page
=> Fixed Modal Popup

src/Pages/HostelApplication.jsx
- Removed Price from `Hostel Application` Page
=> Removed price from hostel

src/Pages/Admission/Tuition And Scholarship/TuitionAndScholarship.jsx
- Removed Scroll on Tuition and scholarship page
=> Removed Scroll on Tuition and scholarship page

src/Pages/About/Our Team/Media Query/Responsive Management.jsx, src/Pages/About/Our Team/Media Query/Responsive Staff.jsx, src/Pages/About/Our Team/Staff.jsx, src/Pages/Academics/Training.jsx, src/Pages/Home/DiscoverHospitality.jsx, src/components/Navbar.jsx, src/components/Statistics.jsx
- Fixed the height of the navbar
- Interchanged Management's picture on mobile
- Replaced a management picture for mobile
- Changed `Student Graduated` to `Graduated` on Statistics Component
=> FIxed height of navbar

src/Pages/Home/Showcase.jsx
- Fixed the video on the showcase component
=> Fixed video on showcase component

package-lock.json, src/pageLayouts/Home/Blog.jsx
- Updated the date on the culinary course
=> Updated culinary course date

src/components/MobileSideBar.jsx, src/pageLayouts/Home/Showcase.jsx, src/pageLayouts/about/Our Team/Media Query/Responsive Board.jsx, src/pageLayouts/about/Our Team/Media Query/Responsive Management.jsx, src/pageLayouts/about/Our Team/index.jsx, src/pageLayouts/about/index.jsx
- Resized stretched images on showcase
- Fixed links on mobile side bar
- Resized images on mobile board page
=> Updated Production

src/components/MobileSideBar.jsx, src/pageLayouts/Contact.jsx, src/pageLayouts/Home/Showcase.jsx, src/pageLayouts/about/Our Team/Media Query/Responsive Board.jsx, src/pageLayouts/about/Our Team/Media Query/Responsive Management.jsx, src/pageLayouts/about/Our Team/index.jsx, src/pageLayouts/about/index.jsx
=> Fixed Emails

src/components/atoms/Logo.tsx, src/components/layouts/HomepageLayout.tsx, src/components/organisms/Header/Header.tsx, src/components/organisms/Header/Search.tsx, src/components/organisms/MobileSideBar.tsx, src/components/organisms/Navbar/Navbar.tsx, src/components/organisms/Navbar/SideLink.tsx, src/components/organisms/Navbar/constants.tsx, src/pages/home.tsx
- broke top navigations using atomic design
- corrects hydration
=> Rebuild Top navigations

.gitignore, package-lock.json, src/components/AuthGuard.tsx, src/components/AuthProvider.tsx, src/components/UserStatus.tsx, src/components/auth.ts, src/components/layouts/Home/HomepageLayout.tsx, src/pages/_app.tsx, src/pages/admin/home.tsx, src/pages/signin.tsx, src/pages/test.tsx
=> Ft add auth
